config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    get "genre_search" => "menus#search"
    resources :users, only:[:show, :edit, :update] do
     member do
       get :favorites
       get :checks
     end
    end
    resources :menus, only:[:new, :create, :show, :index, :edit, :update, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resource :checks, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
  #退会確認ページ
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #退会保存する
    patch '/users/:id/withrawal' => 'users#withrawal', as: 'withrawal'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    get "genre_search" => "menus#search"
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
        get :checks
      end
    end
    resources :menus, only:[:index, :show, :edit, :update, :destroy] do
      resources :comments, only:[:destroy]
    end
    resources :genres, only:[:index, :create, :edit, :update, :destroy]
  #退会確認ページ
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #退会保存する
    patch '/users/:id/withrawal' => 'users#withrawal', as: 'withrawal'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord

  belongs_to :user
  belongs_to :menu
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :menu

  validates :comment, presence: true

end

app/models/cook.rb
class Cook < ApplicationRecord

  has_one_attached :cook_image

  validates :cooks_count, presence: true
  validates :text, presence: true
  # アソシエーション
  belongs_to :menu

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :menu
end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true
  # アソシエーション
  has_many :menus, ->{order('created_at DESC')}, dependent: :destroy

  def menu_limit
    self.menus.limit(4)
  end
end

app/models/material.rb
class Material < ApplicationRecord

validates :name, presence: true
validates :weigh, presence: true
# アソシエーション
  belongs_to :menu

end

app/models/menu.rb
class Menu < ApplicationRecord

 has_one_attached :image

 # アソシエーション
 belongs_to :genre
 belongs_to :user
 has_many :cooks, dependent: :destroy
 has_many :materials, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :checks, dependent: :destroy
 has_many :comments, dependent: :destroy

 validates :name, presence: true
 validates :explanation, presence: true



 # reject_ifは、入力フォームを追加しているもののすべてが空白の場合にリジェクトする
 # allow_destroyは、入力フォームでこのオブジェクトが削除された際に削除を許可する
 accepts_nested_attributes_for :materials, :cooks, reject_if: :all_blank, allow_destroy: true

 # 引数で渡されたユーザーIDがCheckテーブル内に存在するか確認
 def checked_by?(user)
    checks.exists?(user_id: user.id)
 end

# 引数で渡されたユーザーIDがFavoriteテーブル内に存在するか確認
 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 # 検索方法分岐
  def self.looks(search, word)
      @menu = Menu.where("name LIKE?","%#{word}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # アソシエーション
  has_one_attached :profile_image
  has_many :menus, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_many :comments, dependent: :destroy


  validates :name, presence: true
  validates :email, presence: true

  #退会機能
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@email') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(admin_user_params)
      redirect_to admin_user_path(@user)
    else
      render 'edit'
    end
  end

  #退会機能
  def unsubscribe
    @user = User.find(params[:id])
  end

  def withrawal
    @user = User.find(params[:id])
    if @user.update(is_deleted: true)
      redirect_to admin_root_path
    else
      render 'edit'
    end
  end

   #いいね一覧
  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:menu_id)
    @favorites_menu = Menu.find(favorites)
  end

 #作った一覧
  def checks
    @user = User.find(params[:id])
    checks = Favorite.where(user_id: @user.id).pluck(:menu_id)
    @checks_menu = Menu.find(checks)
  end

  private

  def admin_user_params
    params.require(:user).permit(:profile_image, :name, :email)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path(resource)
    root_path
  end

  def after_sign_out_path(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/checks_helper.rb
module Admin::ChecksHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/cooks_helper.rb
module Admin::CooksHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/materials_helper.rb
module Admin::MaterialsHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/checks.html.erb
<h2>作った一覧</h2>
<div class="menu-index">
  <% @checks_menu.each do |menus| %>
    <div class="menu-box">
      <%= link_to admin_menu_path(menus) do %>
        <% if menus.image.attached? %>
          <%= image_tag menus.image, size: "250x250", class: "menu-image" %><br>
        <% else %>
          <%= image_tag 'no-image.jpg', size: "250x250", class: "menu-image" %><br>
        <% end %>
      <% end %>
      <div class="menu-index-name"><h5><%= menus.name %></h5></div>
      <div class="menu-index-explanation"><%= menus.explanation %></div>
    </div>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<h2 class="main-title">プロフィール編集</h2>
<div class="edit-user">
  <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
  <table class="table-box">
    <tr>
      <th class="text-box">
        <% if @user.profile_image.attached? %>
          <%= image_tag @user.profile_image, size: "150x150", class: "profile_image" %>
        <% else %>
          <%= image_tag 'no-image.jpg', size: "150x150", class: "profile_image" %>
        <% end %>
      </th>
      <td><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></td>
    </tr>
    <tr>
      <th class="text-box"><%= f.label :ニックネーム, class: 'text-title' %></th>
      <td><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ニックネーム"%></td>
    </tr>
    <tr>
      <th class="text-box"><%= f.label :メールアドレス, class: 'text_title' %></th>
      <td><%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス"%></td>
    </tr>
  </table>
  <%= f.submit "変更を保存", class: 'user-submit btn btn-warning' %>
  <% end %>
  <%= link_to '退会する', admin_unsubscribe_path(@user) %>
</div>

app/views/admin/users/favorites.html.erb
<h2>いいね一覧</h2>
<div class="menu-index">
  <% @favorites_menu.each do |favorites| %>
    <div class="menu-box">
      <%= link_to admin_menu_path(favorites) do %>
        <% if favorites.image.attached? %>
          <%= image_tag favorites.image, size: "250x250", class: "menu-image" %><br>
        <% else %>
          <%= image_tag 'no-image.jpg', size: "250x250", class: "menu-image" %><br>
        <% end %>
      <% end %>
      <div class="menu-index-name"><h5><%= favorites.name %></h5></div>
      <div class="menu-index-explanation"><%= favorites.explanation %></div>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<h3 class="main-title">会員一覧</h3>
  <table class="admin-users">
    <thead>
      <tr>
        <th class="user-header">プロフィール画像</th>
        <th class="user-header">名前</th>
        <th class="user-header">メールアドレス</th>
        <th class="user-header">ステータス</th>
      </tr>
    </thead>
    <% @users.each do |users| %>
    <tbody class="user-table">
      <tr class="user-table">
        <td class="user-image">
          <%= link_to admin_user_path(users) do %>
            <% if users.profile_image.attached? %>
             <%= image_tag users.profile_image, size: "100x100", class: "profile_image" %>
            <% else%>
             <%= image_tag 'no-image.jpg', size: "100x100", class: "profile_image" %>
            <% end %>
        </td>
        <td class="user-name"><%= users.name %></td>
        <td class="user-email"><%= users.email %></td>
        <td class="user-stetus">
          <% if users.is_deleted == false %>
           有効
          <% else %>
           退会
          <% end %>
        </td>
          <% end %>
      </tr>
    </tbody>
    <% end %>
  </table>

app/views/admin/users/show.html.erb
<% if @user.profile_image.attached? %>
 <%= image_tag @user.profile_image, size: "150x150", class: "profile_image" %><br>
<% else %>
  <%= image_tag 'no-image.jpg', size: "150x150", class: "profile_image" %><br>
<% end %>
<p><%= @user.name %></p>
<%= link_to 'いいね一覧', favorites_admin_user_path %>
<%= link_to '作った一覧', checks_admin_user_path %>
<%= link_to '編集', edit_admin_user_path(@user) %>
<div class="menu-index">
  <% @user.menus.each do |menu| %>
    <div class="menu-box">
      <%= link_to admin_menu_path(menu) do %>
      <% if menu.image.attached? %>
       <%= image_tag menu.image, size: "150x150", class: "menu-image" %><br>
      <% else %>
       <%= image_tag 'no-image.jpg', size: "150x150", class: "menu-image" %><br>
      <% end %>
      <% end %>
      <div class="menu-index-name"><%= menu.name %></div>
    </div>
  <% end %>
</div>

app/views/admin/users/unsubscribe.html.erb
<h4 class="main-title">本当に退会させますか？</h4>
<div class="unsubscribe">
  <p>退会すると、会員側が会員登録情報や</p>
  <p>これまでの日記が閲覧できなくなります。</p>
  <p>退会する場合は、「退会する」をクリックして下さい。</p>
  <%= link_to '退会しない', admin_user_path(@user) %>
  <%= link_to '退会する', admin_withrawal_path, method: :patch %>
</div>