config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    get "genre_search" => "menus#search"
    resources :users, only:[:show, :edit, :update] do
     member do
       get :favorites
       get :checks
     end
    end
    resources :menus, only:[:new, :create, :show, :index, :edit, :update, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resource :checks, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
  #退会確認ページ
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #退会保存する
    patch '/users/:id/withrawal' => 'users#withrawal', as: 'withrawal'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    get "genre_search" => "menus#search"
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
        get :checks
      end
    end
    resources :menus, only:[:index, :show, :edit, :update, :destroy] do
      resources :comments, only:[:destroy]
    end
    resources :genres, only:[:index, :create, :edit, :update, :destroy]
  #退会確認ページ
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #退会保存する
    patch '/users/:id/withrawal' => 'users#withrawal', as: 'withrawal'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord

  belongs_to :user
  belongs_to :menu
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :menu

  validates :comment, presence: true

end

app/models/cook.rb
class Cook < ApplicationRecord

  has_one_attached :cook_image

  validates :cooks_count, presence: true
  validates :text, presence: true
  # アソシエーション
  belongs_to :menu

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :menu
end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true
  # アソシエーション
  has_many :menus, ->{order('created_at DESC')}, dependent: :destroy

  def menu_limit
    self.menus.limit(4)
  end
end

app/models/material.rb
class Material < ApplicationRecord

validates :name, presence: true
validates :weigh, presence: true
# アソシエーション
  belongs_to :menu

end

app/models/menu.rb
class Menu < ApplicationRecord

 has_one_attached :image

 # アソシエーション
 belongs_to :genre
 belongs_to :user
 has_many :cooks, dependent: :destroy
 has_many :materials, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :checks, dependent: :destroy
 has_many :comments, dependent: :destroy

 validates :name, presence: true
 validates :explanation, presence: true



 # reject_ifは、入力フォームを追加しているもののすべてが空白の場合にリジェクトする
 # allow_destroyは、入力フォームでこのオブジェクトが削除された際に削除を許可する
 accepts_nested_attributes_for :materials, :cooks, reject_if: :all_blank, allow_destroy: true

 # 引数で渡されたユーザーIDがCheckテーブル内に存在するか確認
 def checked_by?(user)
    checks.exists?(user_id: user.id)
 end

# 引数で渡されたユーザーIDがFavoriteテーブル内に存在するか確認
 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 # 検索方法分岐
  def self.looks(search, word)
      @menu = Menu.where("name LIKE?","%#{word}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # アソシエーション
  has_one_attached :profile_image
  has_many :menus, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_many :comments, dependent: :destroy


  validates :name, presence: true
  validates :email, presence: true

  #退会機能
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@email') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController
  before_action :authenticate_admin!

  def index
    @menus = Menu.all
    @genres = Genre.all
  end

  def show
    @menu = Menu.find(params[:id])
    cooks = Cook.where(menu_id: @menu.id)
    @cooks = cooks.order(cooks_count: :ASC)
    @comment = Comment.new
    @genres = Genre.all
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    @menu = Menu.find(params[:id])
    if  @menu.update(menus_params)
      redirect_to admin_menu_path(@menu)
    else
      render 'edit'
    end

  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    redirect_to admin_users_path
  end

  def search
    @genre = Genre.find(params[:format])
    @genres = Genre.all
  end

  private

  def menus_params
    params.require(:menu).permit(:image, :name, :explanation, :user_id, :genre_id,
    materials_attributes: [:id, :name, :weigh, :_destroy],
    cooks_attributes: [:id, :cooks_count, :text, :cook_image, :_destroy])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path(resource)
    root_path
  end

  def after_sign_out_path(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/checks_helper.rb
module Admin::ChecksHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/cooks_helper.rb
module Admin::CooksHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/materials_helper.rb
module Admin::MaterialsHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/menus/_cook_fields.html.erb
<div class="nested-fields">
  <div class="row mx-auto">
    <div class="cook-top">
      <div class="col-6"><%= f.text_field :cooks_count, class: "form-control", placeholder: "順番" %></div>
      <div class="col-3">
          <%= f.file_field :cook_image, placeholder: "メニュー画像", accept: "image/*" %>
      </div>
    </div>
    <div class="offset-1 col-6"><%= f.text_area:text, class: "form-control", placeholder: "作り方" %></div>
    <div class="offset-1 col-1 px-0 w-auto">
      <%= link_to_remove_association "削除", f, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
</div>

app/views/admin/menus/_genre_search.html.erb
<% genres.each do |genre| %>
 <%= link_to admin_genre_search_path(genre.id) do %>
  <%= genre.name %>
 <% end %>
<% end %>

app/views/admin/menus/_material_fields.html.erb
<div class="nested-fields">
  <div class="row mx-auto">
    <div class="col-5"><%= f.text_field :name, class: "form-control", placeholder: "材料名" %></div>
    <div class="col-4"><%= f.text_field :weigh, class: "form-control", placeholder: "計量" %></div>
    <div class="offset-1 col-1 px-0 w-auto">
      <%= link_to_remove_association "削除", f, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
</div>

app/views/admin/menus/edit.html.erb
<h3 class="main-title">メニュー編集ページ</h3>
<%= form_with model: @menu, url: admin_menu_path(@menu) do |f| %>
  <div class="menu-top">
    <div class="menu-new">
      <%= f.file_field :image, placeholder: "メニュー画像", accept: "image/*" %>
      <% if @menu.image.attached? %>
       <%= image_tag @menu.image, size: "150x150", class: "menu-image" %>
      <% else %>
       <%= image_tag 'no-image.jpg', size: "150x150", class: "menu-image" %>
      <% end %>
      <div class="menu-genre">
      <%= f.collection_select :genre_id, Genre.all, :id, :name %>
    </div>
    <div class="col-7"><%= f.text_field :name, placeholder: 'メニュー名', class: 'form-control' %></div>
    <div class="col-10"><%= f.text_area :explanation, placeholder: 'メニュー説明', class: 'form-control' %></div>
    <%= f.submit "変更保存", class: 'btn btn-primary' %>
    </div>
    <div class="menu-new">
      <p>材料</p>
     <div class="menu-materials">
       <%= f.fields_for :materials do |materials_fields| %>
         <%= render "material_fields", f: materials_fields %>
       <% end %>
     </div>

     <div id="detail-association-materials"></div>

     <div>
         <%= link_to_add_association "+材料を追加", f, :materials,
        class: "btn btn-secondary btn-block",
        data: {
        association_insertion_node: '#detail-association-materials',
        association_insertion_method: 'before'
        }%>
     </div>
    </div>
  </div>
     <p>作り方</p>
     <div>
       <div class="menu-cooks">

        <%= f.fields_for :cooks do |cooks_fields| %>

          <%= render "cook_fields", f: cooks_fields %>
        <% end %>
       </div>

       <div id="detail-association-insertion-point"></div>

       <div>
         <%= link_to_add_association "+作り方を追加", f, :cooks,
        class: "btn btn-secondary btn-block",
        data: {
        association_insertion_node: '#detail-association-insertion-point',
        association_insertion_method: 'before'
        }%>
       </div>
     </div>
<% end %>

app/views/admin/menus/index.html.erb
<%= render 'admin/menus/genre_search', genres: @genres %>
<div class="menu-index">
  <% @menus.each do |menus| %>
    <div class="menu-box">
      <%= link_to admin_menu_path(menus) do %>
        <% if menus.image.attached? %>
          <%= image_tag menus.image, size: "250x250", class: "menu-image" %><br>
        <% else %>
          <%= image_tag 'no-image.jpg', size: "250x250", class: "menu-image" %><br>
        <% end %>
      <% end %>
      <div class="menu-index-name"><h5><%= menus.name %></h5></div>
      <div class="menu-index-explanation"><%= menus.explanation.truncate(35) %></div>
    </div>
  <% end %>
</div>

app/views/admin/menus/search.html.erb
<%= render 'admin/menus/genre_search', genres: @genres %>
<div class="menu-index">
  <% @genre.menus.each do |menus| %>
    <div class="menu-box">
      <%= link_to admin_menu_path(menus) do %>
        <% if menus.image.attached? %>
          <%= image_tag menus.image, size: "250x250", class: "menu-image" %>
        <% else %>
          <%= image_tag 'no-image.jpg', size: "250x250", class: "menu-image" %>
        <% end %>
      <% end %>
      <div class="menu-index-name"><h5><%= menus.name %></h5></div>
      <div class="menu-index-explanation"><%= menus.explanation.truncate(35) %></div>
    </div>
  <% end %>
</div>

app/views/admin/menus/show.html.erb
<div class="menu-show-top">
 <div class="menu-show">
   <%= link_to admin_genre_search_path(@genres.ids) do %>
     <%= @menu.genre.name %><br>
   <% end %>
   <% if @menu.image.attached? %>
     <%= image_tag @menu.image, size: "300x300", class: "menu-image" %><br>
   <% else %>
     <%= image_tag 'no-image.jpg', size: "300x300", class: "menu-image" %><br>
   <% end %>
  <h3><%= @menu.name %></h3>
  <h4>メニュー説明</h4>
   <%= @menu.explanation %>

  <div class="favorites_buttons_<%= @menu.id %>">
   <%= render 'admin/favorites/favorite', menu: @menu %>
  </div>

  <div class="checks_buttons_<%= @menu.id %>">
   <%= render 'admin/checks/check', menu: @menu %>
  </div>
   <%= link_to "編集", edit_admin_menu_path(@menu) %>
   <%= link_to "削除する", admin_menu_path(@menu), method: :delete, data: {confirm: "本当に削除しますか？"} %>
 </div>

  <div class="menu-show-materials">
   <p class="menu-show-title">材料</p>
    <% @menu.materials.each do |materials| %>
    <ul class="materials-index">
     <li class="material-show">
      <div><%= materials.name %></div>
      <div><%= materials.weigh %></div>
     </li>
    </ul>
    <% end %>
    <div>
    </div>
  </div>
</div>
<table>
 <p class="menu-show-title">作り方</p>
 <% @cooks.each do |cooks| %>
 <tr>
  <td><%= cooks.cooks_count %></td>
  <td>
   <% if cooks.cook_image.attached? %>
    <%= image_tag cooks.cook_image, size: "150x150", class: "menu-image" %>
   <% else %>
    <%= image_tag 'no-image.jpg', size: "150x150", class: "menu-image" %>
   <% end %>
  </td>
  <td><%= cooks.text %><br></td>
 </tr>
 <% end %>
</table>
<table>
 <p>作成者</p>
 <tr>
  <td>
   <%= link_to admin_user_path(@menu.user) do %>
    <% if @menu.user.profile_image.attached? %>
     <%= image_tag @menu.user.profile_image, size: "100x100", class: "profile_image" %>
    <% else %>
     <%= image_tag 'no-image.jpg', size: "100x100", class: "profile_image" %>
    <% end %>
   <% end %>
  </td>
  <td><%= @menu.user.name %></td>
 </tr>
</table>
<div id="comment_area">
 <p>コメント件数：<%= @menu.comments.count %></p><br>
 <div class="comment-index">
  <%= render 'admin/comments/menu_comment', menu: @menu %>
 </div>
</div>