config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get "search" => "searches#search"
    get "genre_search" => "menus#search"
    resources :users, only:[:show, :edit, :update] do
     member do
       get :favorites
       get :checks
     end
    end
    resources :menus, only:[:new, :create, :show, :index, :edit, :update, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resource :checks, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end
  #退会確認ページ
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #退会保存する
    patch '/users/:id/withrawal' => 'users#withrawal', as: 'withrawal'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    get "genre_search" => "menus#search"
    resources :users, only:[:index, :show, :edit, :update] do
      member do
        get :favorites
        get :checks
      end
    end
    resources :menus, only:[:index, :show, :edit, :update, :destroy] do
      resources :comments, only:[:destroy]
    end
    resources :genres, only:[:index, :create, :edit, :update, :destroy]
  #退会確認ページ
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  #退会保存する
    patch '/users/:id/withrawal' => 'users#withrawal', as: 'withrawal'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord

  belongs_to :user
  belongs_to :menu
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :menu

  validates :comment, presence: true

end

app/models/cook.rb
class Cook < ApplicationRecord

  has_one_attached :cook_image

  validates :cooks_count, presence: true
  validates :text, presence: true
  # アソシエーション
  belongs_to :menu

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user, optional: true
  belongs_to :menu
end

app/models/genre.rb
class Genre < ApplicationRecord

  validates :name, presence: true
  # アソシエーション
  has_many :menus, ->{order('created_at DESC')}, dependent: :destroy

  def menu_limit
    self.menus.limit(4)
  end
end

app/models/material.rb
class Material < ApplicationRecord

validates :name, presence: true
validates :weigh, presence: true
# アソシエーション
  belongs_to :menu

end

app/models/menu.rb
class Menu < ApplicationRecord

 has_one_attached :image

 # アソシエーション
 belongs_to :genre
 belongs_to :user
 has_many :cooks, dependent: :destroy
 has_many :materials, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :checks, dependent: :destroy
 has_many :comments, dependent: :destroy

 validates :name, presence: true
 validates :explanation, presence: true



 # reject_ifは、入力フォームを追加しているもののすべてが空白の場合にリジェクトする
 # allow_destroyは、入力フォームでこのオブジェクトが削除された際に削除を許可する
 accepts_nested_attributes_for :materials, :cooks, reject_if: :all_blank, allow_destroy: true

 # 引数で渡されたユーザーIDがCheckテーブル内に存在するか確認
 def checked_by?(user)
    checks.exists?(user_id: user.id)
 end

# 引数で渡されたユーザーIDがFavoriteテーブル内に存在するか確認
 def favorited_by?(user)
    favorites.exists?(user_id: user.id)
 end

 # 検索方法分岐
  def self.looks(search, word)
      @menu = Menu.where("name LIKE?","%#{word}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # アソシエーション
  has_one_attached :profile_image
  has_many :menus, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :checks, dependent: :destroy
  has_many :comments, dependent: :destroy


  validates :name, presence: true
  validates :email, presence: true

  #退会機能
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@email') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path(resource)
    root_path
  end

  def after_sign_out_path(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/checks_helper.rb
module Admin::ChecksHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/cooks_helper.rb
module Admin::CooksHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>Recipe＿club</p>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<!--会員ログイン-->
 <%= link_to root_path, class: 'logo' do %><div class="logo-image"></div><% end %>
 <div class="link">
  <%= link_to menus_path, class: 'header-link' do %>メニュー一覧<% end %>
  <%= link_to user_path(current_user.id), class: 'header-link' do %>マイページ<% end %>
  <%= link_to destroy_user_session_path,class: 'header-link', method: :delete do %>ログアウト<% end %>
  <%= link_to user_path(current_user.id) do %>
    <% if current_user.profile_image.attached? %>
     <%= image_tag current_user.profile_image, size: "50x50", class: "header-profile-image" %>
    <% else %>
     <%= image_tag 'no-image.jpg', size: "50x50", class: "header-profile-image" %>
    <% end %>
   <% end %>
  <%= render 'layouts/search' %>
 </div>
<% elsif admin_signed_in? %>
<!--管理者ログイン-->
 <%= link_to admin_root_path do %><div class="logo-image"></div><% end %>
 <div class="link">
  <%= link_to admin_menus_path, class: 'header-link' do %>メニュー一覧<% end %>
  <%= link_to admin_users_path, class: 'header-link' do %>会員一覧<% end %>
  <%= link_to admin_genres_path, class: 'header-link' do %>ジャンル一覧<% end %>
  <%= link_to destroy_admin_session_path, class: 'header-link',method: :delete do %>ログアウト<% end %>
  <%= render 'layouts/search' %>
 </div>
<% else %>
<!--ログインしてない-->
 <%= link_to root_path, class: 'logo-iamge' do %><div class="logo-image"></div><% end %>
 <div class="link">

  <%= link_to menus_path, class: 'header-link' do %>メニュー一覧<% end %>
  <%= link_to new_user_registration_path, class: 'header-link' do %>新規登録<% end %>
  <%= link_to user_session_path, class: 'header-link' do %>ログイン<% end %>
  <%= link_to users_guest_sign_in_path, method: :post, class: 'header-link' do %>ゲストログイン<% end %>
  <%= link_to new_admin_session_path, class: 'header-link' do %>管理者ログイン<% end %>
 </div>


<% end %>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word, placeholder: "メニュー" %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
<% else admin_signed_in? %>
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word, placeholder: "メニュー" %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render 'layouts/header' %></header>
    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>